version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  user:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-user
    command: npm run start:prod
    ports:
      - 3000:3000
    depends_on:
      - user-mongo
      - user-redis
      - kafka
    environment:
      NODE_ENV: development
      PORT: 3000
      PATH_PREFIX: api
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: user
      MONGO_URI: mongodb://admin:admin@user-mongo:27017/user?authSource=admin
      REDIS_HOST: user-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REFRESH_TOKEN_EXPIRES_IN: 86400
      REFRESH_TOKEN_SECRET: 8d9570c0a7eee37ffb56df8570988709
      ACCESS_TOKEN_EXPIRES_IN: 600
      ACCESS_TOKEN_SECRET: 165d042e466fcff0ce6914dae33e5b93
      RE_CAPTCHA_SITE_KEY:
      RE_CAPTCHA_SECRET_KEY:
      SUPER_ADMIN_MOBILE: 09301111111
      ISC_SECRET: "x+nEyN8iupCAFOGadYW1NQIkrpkzJY56khFBOFl0ztoMQ8QyWAwtJpUxKaYRulZ3P/pinGpT8Acr57WI2bWnmA=="
      TRANSACTION_BASE_URL: http://transaction:3002/api
    volumes:
      - user:/app
      - /app/node_modules
    networks:
      - default

  user-mongo:
    image: mongo
    restart: always
    volumes:
      - user-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAM: admin
      MONGO_INITDB_ROOT_PASSWOR: admin
    networks:
      - default

  user-redis:
    image: redis:alpine
    restart: always
    command: redis-server
    volumes:
      - user-redis:/data
    networks:
      - default

  product:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-product
    command: npm run start:prod
    ports:
      - 3001:3000
    depends_on:
      - product-mongo
      - product-redis
      - kafka
    environment:
      NODE_ENV: development
      PORT: 3000
      PATH_PREFIX: api
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: product
      MONGO_URI: mongodb://admin:admin@product-mongo:27017/product?authSource=admin
      REDIS_HOST: product-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      ACCESS_TOKEN_SECRET: 165d042e466fcff0ce6914dae33e5b93
      ISC_SECRET: "x+nEyN8iupCAFOGadYW1NQIkrpkzJY56khFBOFl0ztoMQ8QyWAwtJpUxKaYRulZ3P/pinGpT8Acr57WI2bWnmA=="
      TRANSACTION_BASE_URL: http://transaction:3000/api
    volumes:
      - product:/app
      - /app/node_modules
    networks:
      - default

  product-mongo:
    image: mongo
    restart: always
    volumes:
      - product-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAM: admin
      MONGO_INITDB_ROOT_PASSWOR: admin
    networks:
      - default

  product-redis:
    image: redis:alpine
    restart: always
    command: redis-server
    volumes:
      - product-redis:/data
    networks:
      - default

  transaction:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-transaction
    command: npm run start:prod
    ports:
      - 3002:3000
    depends_on:
      - transaction-mongo
      - kafka
    environment:
      NODE_ENV: development
      PORT: 3000
      PATH_PREFIX: api
      DOMAIN: http://127.0.0.1:3002
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: transaction
      MONGO_URI: mongodb://admin:admin@transaction-mongo:27017/transaction?authSource=admin
      ACCESS_TOKEN_SECRET: 165d042e466fcff0ce6914dae33e5b93
      ZIBAL_BASE_URL: https://gateway.zibal.ir
      ZIBAL_MERCHANT: zibal
      ISC_SECRET: "x+nEyN8iupCAFOGadYW1NQIkrpkzJY56khFBOFl0ztoMQ8QyWAwtJpUxKaYRulZ3P/pinGpT8Acr57WI2bWnmA=="
    volumes:
      - transaction:/app
      - /app/node_modules
    networks:
      - default

  transaction-mongo:
    image: mongo
    restart: always
    volumes:
      - transaction-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAM: admin
      MONGO_INITDB_ROOT_PASSWOR: admin
    networks:
      - default

volumes:
  user:
    driver: local
  user-mongo:
    driver: local
  user-redis:
    driver: local
  product:
    driver: local
  product-mongo:
    driver: local
  product-redis:
    driver: local
  transaction:
    driver: local
  transaction-mongo:
    driver: local
